# Generated by Django 5.1.6 on 2025-07-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_destination_chatmessage_tripplanrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripplanrequest",
            name="daily_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Daily budget",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tripplanrequest",
            name="experience_style",
            field=models.CharField(
                blank=True, help_text="Experience style", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="tripplanrequest",
            name="interests",
            field=models.TextField(
                blank=True, help_text="interests and activities", null=True
            ),
        ),
        migrations.AddField(
            model_name="tripplanrequest",
            name="number_of_travelers",
            field=models.IntegerField(default=1, help_text="Number of travelers"),
        ),
        migrations.AddField(
            model_name="tripplanrequest",
            name="transportation_preferences",
            field=models.CharField(
                blank=True,
                help_text="Transportation preferences",
                max_length=255,
                null=True,
            ),
        ),
    ]
