# Generated by Django 5.1.6 on 2025-08-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_ticket_ticketmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripplanrequest",
            name="destination_country",
            field=models.CharField(
                blank=True, help_text="Destination country", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="tripplanrequest",
            name="destination_place_id",
            field=models.CharField(
                blank=True, help_text="Google Places ID", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tripplanrequest",
            name="destination",
            field=models.CharField(
                help_text="Destination city or place", max_length=255
            ),
        ),
    ]
