# Generated by Django 5.1.6 on 2025-08-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_tripplanrequest_destination_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="google_profile_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="is_google_user",
            field=models.BooleanField(default=False),
        ),
    ]
