# Generated by Django 5.1.6 on 2025-08-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_user_avatar_url_user_google_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripplanrequest",
            name="budget",
            field=models.DecimalField(
                decimal_places=2, help_text="Budget (USD)", max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="tripplanrequest",
            name="daily_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Daily budget (USD per person)",
                max_digits=14,
                null=True,
            ),
        ),
    ]
